services:
  db:
    image: postgres
    container_name: safehaven_db
    environment:
      POSTGRES_DB: safeHaven
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - safehaven_network

networks:
  safehaven_network:

volumes:
  postgres_data: